import { DynamoDBDocumentClient } from '@aws-sdk/lib-dynamodb';
export declare const docClient: DynamoDBDocumentClient;
export declare const AVATAR_TABLE: string;
export declare const PIG_SPECIES_TABLE: string;
export declare const EVOLUTION_ROUTE_TABLE: string;
export declare const SKILL_TABLE: string;
export declare const AUDIT_LOG_TABLE: string;
export declare const GAME_CONFIG_TABLE: string;
export declare const USER_PROFILES_TABLE: string;
export declare const ACTIVITY_RECORD_TABLE: string;
